### ISSUE TITLE
Rating object output string (letters)

### ISSUE THREAD

**Issue by TrishaDes** [LordOfPolls/Rule34-API-Wrapper#11]
ik that lord said that on the rating object the output is mainly e, but, this isn't adjustable?

**Comment by LordOfPolls** [comment]
I'll add this to the next release

**Comment by TrishaDes** [comment]
thanks, i also want to ask if it will be added a tag blacklist

**Comment by LordOfPolls** [comment]
A tag blacklist?

**Comment by TrishaDes** [comment]
yep! is it possible?

**Comment by LordOfPolls** [comment]
I don't know what you mean. As in you want to be able to block a customisable list of tags? Then no, that's not in the scope of an API and is something you should implement in your own code. 

If that's not what you mean, you'll have to explain

**Comment by TrishaDes** [comment]
Yep, that is what i was meaning, thanks, i'll implement it by myself
