### ISSUE TITLE
totalImages() missing 1 required positional argument: 'tags'

### ISSUE THREAD

**Issue by whitetrashyt** [LordOfPolls/Rule34-API-Wrapper#13]
Hopefully, this isn't me being stupid, however, i've been having problems using totalimages.

First, i tried to use it in order to gauge the max PID i can go up to:
`def pidfix(str): # fixes our pid random generator with our max ammount
    print(str) # this is for debugging purposes, will remove later.
    int = r.totalImages(str) # polls how many images there are for the specified tags
    stepo = int / 42 # there are 42 posts on a page, so divide this by 42
    newpid = round(stepo) # rounds these so we dont have insane decimals
    return newpid`
This threw the same error when coupled with `newint = pidfix(tagse)`
(Tagse was not empty, i assure you)
I then tried using a test script to see if it was my own fault:
`import rule34

r = rule34.Sync

r.totalImages('furry')`
Same issue. My apologies if its just me being an idiot but i cant exactly figure out the issue,
i can send the whole script if needed.

**Comment by whitetrashyt** [comment]
oh, those got jumbled, screenshots instead
![First attempt](https://user-images.githubusercontent.com/34116619/89122434-11149a80-d495-11ea-8238-70f9e9ec2451.PNG)
![What i used to run the first attempt](https://user-images.githubusercontent.com/34116619/89122435-11ad3100-d495-11ea-9daf-9d03e8190db0.PNG)
![third attempt](https://user-images.githubusercontent.com/34116619/89122436-11ad3100-d495-11ea-87b3-47dcfe3cb3a2.PNG)

**Comment by LordOfPolls** [comment]
Have you tried `r.totalImages(tags="furry")`. That should make it behave correctly, I have a pretty good idea whats wrong and shall add it to my To-do list

**Comment by whitetrashyt** [comment]
That worked, however, after changing it, i got the same error, but instead the missing argument was 'self'
![error4](https://user-images.githubusercontent.com/34116619/89127096-fc49fe00-d4b8-11ea-8a6a-b9afeb54bcba.PNG)
presume this is something on my own end again but i haven't got a clue

**Comment by LordOfPolls** [comment]
you forgot to put brackets next to the sync decloration. ie `r= rule34.Sync()`

**Comment by whitetrashyt** [comment]
lmao my bad, thank you. works as intended
