### ISSUE TITLE
The module raised asyncio.exceptions.CancelledError, and unclosed connection

### ISSUE THREAD

**Issue by ReyterYT** [LordOfPolls/Rule34-API-Wrapper#15]
```py
Traceback (most recent call last):
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
asyncio.exceptions.TimeoutError
```
![Screenshot_2020-09-17-14-54-01-50.png](https://user-images.githubusercontent.com/59440735/93437111-cc827880-f8f5-11ea-97d4-09660842fd55.png)

my code:
```py
rul34 = rule34.Rule34(self.bot.loop)
        file = await rul34.getImages(tag)
        if not file:
            await ctx.send("No images found")
            return
        file = random.choice(file).file_url
        card = Embed(colour=ctx.author.colour)
        card.set_image(url=file)
        await ctx.send(embed=card)
```

This worked not long ago and suddenly doesn't work for some reason

**Comment by LordOfPolls** [comment]
Can you send a full traceback, rather than a cropped screenshot? It makes it really hard to diagnose with only a partial traceback

**Comment by ReyterYT** [comment]
![Screenshot_2020-09-17-14-53-57-15_84d3000e3f4017145260f7618db1d683.png](https://user-images.githubusercontent.com/59440735/93594561-47c05900-f9e0-11ea-995c-999b271809b2.png)

**Comment by ReyterYT** [comment]
Suddenly it started working, both Async and Non-Async didn't work before tho. Im still curious why, but i will closed this because i can connect again.
