### ISSUE TITLE
I don't know what the hell I am doing 

### ISSUE THREAD

**Issue by nonetrix** [LordOfPolls/Rule34-API-Wrapper#16]
trying to add this to a discord bot all I want it to do is pick a random image here is my code and the output

code
`import asyncio
import rule34
loop = asyncio.get_event_loop()
rule34 = rule34.Rule34(loop)
data = loop.run_until_complete(rule34.getImages("lmao"))
print(data)
`

wtf:
`Traceback (most recent call last):
  File "lol.py", line 5, in <module>
    data = loop.run_until_complete(rule34.getImages("lmao"))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/nonetrix/.local/lib/python3.8/site-packages/rule34/rule34.py", line 192, in getImages
    image.parse(post)
  File "/home/nonetrix/.local/lib/python3.8/site-packages/rule34/objectClasses.py", line 44, in parse
    self.height = int(post['@height']) if '@height' in post else None
TypeError: string indices must be integers
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb6ec5fcfd0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fb6eb904e20>, 21107.873550848)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fb6ec5fcf70>`

**Comment by LordOfPolls** [comment]
If you're using ``discord.py`` you want this:

```python
import rule34
loop = bot.loop
r34 = rule34.Rule34(loop)
data = await r34.getImages("query")
```

I would suggest you do some research on asynchronous coroutines, as the vast majority of bot development is based in them. If this doesn't resolve the issue, feel free to re-open this issue, and i'll see if i can reproduce your issue and fix it

**Comment by nonetrix** [comment]
I could not get it to work pls don't roast me too much I suck at python here is all my code feel free to show me where I could also inprove it

`
output: `Traceback (most recent call last):
  File "useless.py", line 14, in <module>
    loop = bot.loop
NameError: name 'bot' is not defined


------------------
(program exited with code: 1)
Press return to continue
`

`import discord
import asyncio
import random
import requests
import rule34
import psutil
from discord.ext import commands

client = commands.Bot(command_prefix="!u ")
waifu = open('./text/waifu.txt', 'r')
lines_waifu = waifu.readlines()
commands = open('./text/commands.txt', 'r')
commands_read = commands.read()
loop = bot.loop
r34 = rule34.Rule34(loop)


@client.event
async def on_ready():
	print("Bot logged in!")


	#Animal commands
	
	
	#sends a cat
	@client.command()
	async def cat(ctx):
		response = requests.get('https://some-random-api.ml/img/cat')
		data = response.json()
		await ctx.send(data['link'])
		print("sent cat")


	#sends a dog
	@client.command()
	async def dog(ctx):
		response = requests.get('https://some-random-api.ml/img/dog')
		data = response.json()
		await ctx.send(data['link'])
		print("sent dog")


	#sends a panda
	@client.command()
	async def panda(ctx):
		response = requests.get('https://some-random-api.ml/img/panda')
		data = response.json()
		await ctx.send(data['link'])
		print("sent panda")


	# sends a bird
	@client.command()
	async def bird(ctx):
		response = requests.get('https://some-random-api.ml/img/birb')
		data = response.json()
		await ctx.send(data['link'])
		print("sent bird")


	#sends a koala
	@client.command()
	async def koala(ctx):
			response = requests.get('https://some-random-api.ml/img/koala')
			data = response.json()
			await ctx.send(data['link'])
			print("sent koala")


	#sends a fox
	@client.command()
	async def fox(ctx):
			response = requests.get('https://some-random-api.ml/img/fox')
			data = response.json()
			await ctx.send(data['link'])
			print("sent fox")
		
			
	#Anime commands
	
	
	#sends a pikachu
	@client.command()
	async def pikachu(ctx):
			response = requests.get('https://some-random-api.ml/img/pikachu')
			data = response.json()
			await ctx.send(data['link'])
			print("sent pikachu")
	
	
	#sends a random waifu
	@client.command()
	async def waifu(ctx):
			await ctx.send(random.choice(lines_waifu))
			print("sent waifu")
		
		
	#Meme commands
		
		
	#sends a random meme
	@client.command()
	async def meme(ctx):
			response = requests.get('https://some-random-api.ml/meme')
			data = response.json()
			await ctx.send(data['image'])
			print("sent meme")


	#info
	
	
	#sends all commands
	@client.command()
	async def commands(ctx):
			await ctx.send(commands_read)
			print()
	
	
	#sends system load
	@client.command()
	async def checkload(ctx):
			cpu = psutil.cpu_percent()
			ram = psutil.virtual_memory()
			await ctx.send(cpu)
			await ctx.send(ram)
			print("sent system load")
			
	#sends system load
	@client.command()
	async def hentea(ctx):
			data = await r34.getImages("query")
			print(data)


client.run('no lol get fricked gg')
`
