### ISSUE TITLE
I still don't know what the hell I am doing 

### ISSUE THREAD

**Issue by nonetrix** [LordOfPolls/Rule34-API-Wrapper#17]
bad poorly made code 0/10 bloat RMS would be mad: https://pastebin.com/z7FdtQF4

error that's easy to fix but I'm too dumb because I don't even know the basics of python just crappy APIs: `NameError: name 'bot' is not defined`

**Comment by LordOfPolls** [comment]
The error is telling you what's wrong. I'd suggest you learn how to program in python properly, before you tackle making an asynchronous bot. 

Regardless, the error has nothing to do with rule34. You defined your bot under the variable ``client`` (line 8). Then tried to call your bot with the variable ``bot`` (line 13)
