### ISSUE TITLE
String indices must be integers error

### ISSUE THREAD

**Issue by gbdfscxvgnfhfdvv** [LordOfPolls/Rule34-API-Wrapper#20]
i get the **string must be integers** error for some images

i only have 1 instance of it happening and it's for [this image](https://wimg.rule34.xxx//images/1008/04ab2606c1a9907fcbd3cc5ea7fb559a08f05f65.jpg) (I'm really sorry for objecting your eyes to this)

it's a parsing error because the "post" in rule34.py
```image.parse(post)```
 for this image is just "@height"

**Comment by LordOfPolls** [comment]
Through my testing, this appears to be an issue on rule34's side. Im adding some error handling to catch rule34 sending invalid data
