### ISSUE TITLE
neither method of requiring/importing works..?

### ISSUE THREAD

**Issue by ex7ase** [LordOfPolls/Rule34-API-Wrapper#22]
I tried:
```js
const rule34 = require("rule34").Sync();
```

and:

```js
const rule34 = require("rule34");
const r34 = rule34.Sync();
```

neither worked. maybe i'm doing it wrong? this is for a bot written in javascript.
note: it said that sync wasnt a function.

**Comment by LordOfPolls** [comment]
Hi, I think youre commenting on the wrong library. This is a python module, not js

**Comment by ex7ase** [comment]
oh sorry, this is a friends account and I’m new to coding. he’s letting me
view his private repositories. thanks for the response!

**Comment by LordOfPolls** [comment]
No problem. Best of luck learning to code
