### ISSUE TITLE
Error when pulling from a tag with only 1 image

### ISSUE THREAD

**Issue by OliMations** [LordOfPolls/Rule34-API-Wrapper#24]
See the traceback below
> Traceback (most recent call last):
>   File "", line 85, in wrapped
>     ret = await coro(*args, **kwargs)
>   File "", line 51, in rule34
>     await r34.getImages(tags=desire, randomPID=True)
>   File "/home/ollie/.local/lib/python3.7/site-packages/rule34/rule34.py", line 201, in getImages
>     image.parse(post)
>   File "/home/ollie/.local/lib/python3.7/site-packages/rule34/objectClasses.py", line 58, in parse
>     self.has_children = False if post['@has_children'] == "false" else True
> TypeError: string indices must be integers
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 902, in invoke
>     await ctx.command.invoke(ctx)
>   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 864, in invoke
>     await injected(*ctx.args, **ctx.kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 94, in wrapped
>     raise CommandInvokeError(exc) from exc
> discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: string indices must be integers

I am using Python 3.7 with the most recent version of this package on pypi. Running on ubuntu 18.04.5

To reproduce this try querying a tag with only one result such as "rule34" or "quit" using the standard async function provided and it should throw a similar error to the one above, it doesn't appear to matter whether random PID is enabled or not.

I'm not sure what else to include, so if you need any more info... I'm here!

**Comment by LordOfPolls** [comment]
I believe rule34 has changed something about their API. Im going to fix the issue tomorrow morning (its midnight here)

**Comment by OliMations** [comment]
yeah, it was almost midnight when I commented that. Thanks for the quick response.
