### ISSUE TITLE
UnboundLocalError: local variable 'rule34' referenced before assignment

### ISSUE THREAD

**Issue by TooProximity** [LordOfPolls/Rule34-API-Wrapper#7]
Might be my slow brain, however after coding a simple command to call the Rule34 API it raises this exception;

UnboundLocalError: local variable 'rule34' referenced before assignment

My code is as follows;

----------

@commands.command()
    async def r34(self, ctx, *, text:str):
        """Query Rule34 for results from a search"""

        #Checking for NSFW tag on channel.
        if ctx.channel.is_nsfw():
            author = ctx.message.author.name
            r = ['+1', '-1']
            loop = asyncio.get_event_loop()
            rule34 = rule34.Rule34(loop)
            data = loop.run_until_complete(r34.getImageURLS("{}").format(text))
            embed=discord.Embed(title="Search Results for {} - Click here for the fullsize image or if it doesn't load.".format(text), url=data, color=0x3decff)
            embed.set_image(url=data)
            embed.set_footer("Search Requested by **{}**".format(author))
            msg = await ctx.send(embed=embed)

-------------

Not positive as to what i've done wrong.

**Comment by LordOfPolls** [comment]
Look at these 2 lines, what looks wrong to you. 

```py
rule34 = rule34.Rule34(loop)
data = loop.run_until_complete(r34.getImageURLS("{}").format(text))
```

**Comment by TooProximity** [comment]
Oh yes, completely disregard that by all means;

loop.run_until_complete(r34.getImageURLS("{}").format(text))

Should be;

loop.run_until_complete(rule34.getImageURLS("{}").format(text))

If that's what you're getting act, however that's not the cause of my exception.

**Comment by LordOfPolls** [comment]
Well besides that issue, i cant see anything wrong. Make sure youre importing the module at the top of your file. If you need more help, ill need to see the whole file

**Comment by TooProximity** [comment]
Sure thing, my whole file is as follows;

```
import discord
import aiohttp
import asyncio
import rule34
from redbot.core import commands
class nsfw(commands.Cog):
    """Pornography Commands - Can only be used in **NSFW** channels."""

    def __init__(ctx, bot):
        ctx.bot = bot

    @commands.command()
    async def r34(self, ctx, *, text:str):
        """Query Rule 34 for results from a search"""

        #Checking for NSFW tag on channel.
        if ctx.channel.is_nsfw():
            author = ctx.message.author.name
            r = ['+1', '-1']
            loop = asyncio.get_event_loop()
            rule34 = rule34.Rule34(loop)
            data = loop.run_until_complete(rule34.getImageURLS("{}").format(text))
            embed=discord.Embed(title="Search Results for {} - Click here for the fullsize image or if it doesn't load.".format(text), url=data, color=0x3decff)
            embed.set_image(url=data)
            embed.set_footer("Search Requested by **{}**".format(author))
            msg = await ctx.send(embed=embed)
        #If missing NSFW tag will produce below message.
        else:
            embed=discord.Embed(title=":warning:", color=0xFF2F05)
            embed.add_field(name="You cannot use that command here!", value="This can only be used in channels marked as `NSFW`", inline=False)
            await ctx.send(embed=embed)
        
def setup(bot):
    bot.add_cog(nsfw(bot))

**Comment by LordOfPolls** [comment]
Sorry for slow replies, been busy with other projects.

The only possible idea ive had is it might be because youre importing ``rule34`` then overwriting ``rule34`` while calling ``rule34``

```py
import rule34
[...]
rule34 = rule34.Rule34(loop)
```

If thats the case, using ``Rule34 = rule34.Rule34(loop)`` should fix it
