### ISSUE TITLE
AttributeError: module 'rule34' has no attribute 'Sync'

### ISSUE THREAD

**Issue by crazytaj** [LordOfPolls/Rule34-API-Wrapper#9]
my python code is this: 
`import rule34
import sys
stringToSearch = ''
for arg in sys.argv :
    stringToSearch = stringToSearch + ' ' + arg
rule34 = rule34.Sync()
rule34.getImages(stringToSearch)
`
but im getting this error when i run it : AttributeError: module 'rule34' has no attribute 'Sync'
i have installed rule34 with pip, and i cant figure out what is wrong here.

**Comment by LordOfPolls** [comment]
Are there any files called "rule34.py" in the project directory?

**Comment by crazytaj** [comment]
yeah, thats the file i am running

**Comment by crazytaj** [comment]
i just renamed it, and now i am getting a different error.
Traceback (most recent call last):
  File "rule34program.py", line 1, in <module>
    import rule34
ImportError: bad magic number in 'rule34': b'\x03\xf3\r\n'

**Comment by LordOfPolls** [comment]
This should help, and explain the cause better than I ever could

https://stackoverflow.com/a/514395
